# Generated by Django 2.2 on 2019-06-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='name',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
