# Generated by Django 2.2 on 2019-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_locations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='distance',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
