# Generated by Django 2.2 on 2019-07-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=250)),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Posts',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=250)),
                ('number', models.IntegerField()),
                ('text', models.CharField(default='article topic goes here', max_length=5000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=250)),
                ('number', models.IntegerField()),
                ('text', models.CharField(default='article subtopic goes here', max_length=5000)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Topic')),
            ],
        ),
    ]
