# Generated by Django 2.2 on 2019-06-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
