# Generated by Django 2.2 on 2019-07-19 10:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+17853701281", max_length=15, region='US', unique=True),
            preserve_default=False,
        ),
    ]
