# Generated by Django 2.2 on 2019-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190719_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pickup',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
