# Generated by Django 2.2 on 2019-06-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='slot',
            field=models.DateTimeField(default='2019-07-07 16:00'),
        ),
    ]
