# Generated by Django 2.2 on 2019-06-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='slot',
            field=models.DateTimeField(default='2019-07-07 16:00', unique=True),
        ),
    ]
