# Generated by Django 2.2 on 2019-07-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20190626_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='slot',
            field=models.DateTimeField(unique=True),
        ),
    ]
