# Generated by Django 2.2 on 2019-06-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='slot',
            field=models.DateTimeField(default='2019-07-07 05:00'),
        ),
    ]
