# Generated by Django 2.2 on 2019-06-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='slot',
            field=models.DateTimeField(null=True, unique=True),
        ),
    ]
