# Generated by Django 2.2 on 2019-07-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190624_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
